name: 'Setup Conan'
inputs:
  compiler:
    description: 'Used compiler'
    required: true
  compiler-version:
    description: 'Used compiler version'
    required: true
  shell:
    description: 'Used shell for executing commands'
    required: true
  version:
    description: 'Version to install'
    required: false
    default: 2.2.1
outputs:
  conan-profile:
    value: conan/${{ inputs.compiler }}-${{ inputs.compiler-version }}
runs:
  using: 'composite'
  steps:
    - name: Install Conan
      uses: turtlebrowser/get-conan@v1.2
      with:
        version: ${{ inputs.version }}

    - name: Install Conan configuration files
      shell: ${{ inputs.shell }}
      run: |
        conan config install conan/global.conf

    - name: Detect default profile
      shell: ${{ inputs.shell }}
      run: |
        conan profile detect --force

    - name: Checkout private recipes repository
      uses: actions/checkout@v4
      with:
        repository: jan-kelemen/conan-recipes
        path: recipes

    - name: Override public Conan recipes
      shell: ${{ inputs.shell }}
      run: |
       conan create recipes/recipes/sdl/all --version 2.30.1 --build=missing

    - name: Override Linux specific public Conan recipes
      if: ${{ inputs.compiler == 'clang' || inputs.compiler == 'gcc' }}
      shell: ${{ inputs.shell }}
      run: |
       conan create recipes/recipes/pulseaudio/meson --version 17.0 --build=missing
