name: 'Setup Conan'
inputs:
  version:
    description: 'Version to install'
    required: false
    default: 2.2.1
  shell:
    description: 'Used shell for executing commands'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Conan
      uses: turtlebrowser/get-conan@v1.2
      with:
        version: ${{ inputs.version }}

    - name: Detect default profile
      shell: ${{ inputs.shell }}
      run: |
        conan profile detect --force

    - name: Checkout private recipes repository
      uses: actions/checkout@v4
      with:
        repository: jan-kelemen/conan-recipes
        path: recipes

    - name: Override public Conan recipes
      shell: ${{ inputs.shell }}
      run: |
       cd recipes/recipes/sdl/all
       conan create . --version 2.30.1 --build=missing
